version: "3.9"

services:
  frontend:
    container_name: stockapp
    restart: always
    build: .
    ports:
    #  - '4300:4300'
    #  - '4301:4301'
       - '8080:8080'

    depends_on:
      - mongodb
      - redis
      - neo4j

  mongodb:
    image: mongo:latest
    container_name: mongocontainer
    environment:
      - MONGO_INITDB_DATABASE=mongostock
      - MONGO_INITDB_ROOT_USERNAME=mongostock
      - MONGO_INITDB_ROOT_PASSWORD=ADBsummer2022!
    volumes:
      - ./mongodb:/data/mongodb/
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend
 
  redis:
    image: redis:7.0.0-alpine
    container_name: rediscontainer
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
    networks:
      - backend
    volumes:
      - redis:/data/redis/
 
  neo4j:
    image: neo4j:community
    container_name: neo4jcontainer
    network_mode: "bridge"
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment: 
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G

networks:
  backend:
    driver: bridge

volumes:
  mongodb:
  redis:
